/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autorennen;

/**
 *
 * @author bbsuser
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        
        initComponents();
        Spielregeln spielregeln=new Spielregeln();
        this.spielregeln=spielregeln;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFahrbahn1 = new javax.swing.JPanel();
        jLabelAutoSpieler1 = new javax.swing.JLabel();
        jPanelFahrbahn2 = new javax.swing.JPanel();
        jLabelAutoSpieler2 = new javax.swing.JLabel();
        jButtonBremsenSpieler1 = new javax.swing.JButton();
        jButtonBremsenSpieler2 = new javax.swing.JButton();
        jButtonGasGebenSpieler1 = new javax.swing.JButton();
        jButtonGasGebenSpieler2 = new javax.swing.JButton();
        jButtonWeiterSpieler1 = new javax.swing.JButton();
        jButtonWeiterSpieler2 = new javax.swing.JButton();
        jProgressBarSpeedSpieler2 = new javax.swing.JProgressBar();
        jTextFieldNextStepSpieler2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFahrbahn1.setBackground(new java.awt.Color(0, 204, 0));

        jLabelAutoSpieler1.setBackground(new java.awt.Color(153, 0, 0));
        jLabelAutoSpieler1.setForeground(new java.awt.Color(153, 0, 0));
        jLabelAutoSpieler1.setText("jLabel1");

        javax.swing.GroupLayout jPanelFahrbahn1Layout = new javax.swing.GroupLayout(jPanelFahrbahn1);
        jPanelFahrbahn1.setLayout(jPanelFahrbahn1Layout);
        jPanelFahrbahn1Layout.setHorizontalGroup(
            jPanelFahrbahn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFahrbahn1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelAutoSpieler1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelFahrbahn1Layout.setVerticalGroup(
            jPanelFahrbahn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFahrbahn1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAutoSpieler1)
                .addContainerGap())
        );

        jPanelFahrbahn2.setBackground(new java.awt.Color(204, 0, 0));

        jLabelAutoSpieler2.setForeground(new java.awt.Color(51, 153, 0));
        jLabelAutoSpieler2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutoSpieler2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmw-mini-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFahrbahn2Layout = new javax.swing.GroupLayout(jPanelFahrbahn2);
        jPanelFahrbahn2.setLayout(jPanelFahrbahn2Layout);
        jPanelFahrbahn2Layout.setHorizontalGroup(
            jPanelFahrbahn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFahrbahn2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelAutoSpieler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFahrbahn2Layout.setVerticalGroup(
            jPanelFahrbahn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFahrbahn2Layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jLabelAutoSpieler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jButtonBremsenSpieler1.setText("bremsen");

        jButtonBremsenSpieler2.setText("bremsen");
        jButtonBremsenSpieler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBremsenSpieler2ActionPerformed(evt);
            }
        });

        jButtonGasGebenSpieler1.setText("gasgeben");

        jButtonGasGebenSpieler2.setText("gasgeben");
        jButtonGasGebenSpieler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGasGebenSpieler2ActionPerformed(evt);
            }
        });

        jButtonWeiterSpieler1.setText("weiter");

        jButtonWeiterSpieler2.setText("weiter");
        jButtonWeiterSpieler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWeiterSpieler2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBremsenSpieler1)
                    .addComponent(jButtonGasGebenSpieler1)
                    .addComponent(jButtonWeiterSpieler1))
                .addGap(18, 18, 18)
                .addComponent(jPanelFahrbahn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelFahrbahn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBremsenSpieler2)
                    .addComponent(jButtonGasGebenSpieler2)
                    .addComponent(jProgressBarSpeedSpieler2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWeiterSpieler2)
                    .addComponent(jTextFieldNextStepSpieler2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonWeiterSpieler1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGasGebenSpieler1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBremsenSpieler1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jProgressBarSpeedSpieler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNextStepSpieler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonWeiterSpieler2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonGasGebenSpieler2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonBremsenSpieler2))
                        .addComponent(jPanelFahrbahn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelFahrbahn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGasGebenSpieler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGasGebenSpieler2ActionPerformed

        this.nextStepSpieler2 = "gasgeben";
        this.jTextFieldNextStepSpieler2.setText(this.nextStepSpieler2);

    }//GEN-LAST:event_jButtonGasGebenSpieler2ActionPerformed

    private void jButtonBremsenSpieler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBremsenSpieler2ActionPerformed

        this.nextStepSpieler2 = "bremsen";
        this.jTextFieldNextStepSpieler2.setText(this.nextStepSpieler2);

    }//GEN-LAST:event_jButtonBremsenSpieler2ActionPerformed

    private void jButtonWeiterSpieler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWeiterSpieler2ActionPerformed
 
    int xCoord = this.jLabelAutoSpieler2.getLocation().x;
    int yCoord = this.jLabelAutoSpieler2.getLocation().y;
     
      if (!this.nextStepSpieler2.equals("")) {
            if (this.nextStepSpieler2.equals("bremsen")) {
                if (this.speedSpieler2 - 3 >= 0){
                    this.speedSpieler2 = this.speedSpieler2 - 3;
                    yCoord = yCoord - this.speedSpieler2;
                } else {
                    this.speedSpieler2 = 0;
                }

            } else {
                this.speedSpieler2 = this.speedSpieler2 + 3;
                yCoord = yCoord - this.speedSpieler2;
            }
        }
        this.nextStepSpieler2 = "";

        if (yCoord <= 0) {
            System.out.println("Spieler 2 Gewonnen!");
            this.nextStepSpieler2 = "GEWONNEN!";
            yCoord = 0;
        }
        this.jLabelAutoSpieler2.setLocation(xCoord, yCoord);
        this.jProgressBarSpeedSpieler2.setValue(this.speedSpieler2);
        this.jTextFieldNextStepSpieler2.setText(this.nextStepSpieler2);

    }//GEN-LAST:event_jButtonWeiterSpieler2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    //Eigene Variablen
    private String nextStepSpieler2 = "";
    private int speedSpieler2 = 6;
    private Spielregeln spielregeln;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBremsenSpieler1;
    private javax.swing.JButton jButtonBremsenSpieler2;
    private javax.swing.JButton jButtonGasGebenSpieler1;
    private javax.swing.JButton jButtonGasGebenSpieler2;
    private javax.swing.JButton jButtonWeiterSpieler1;
    private javax.swing.JButton jButtonWeiterSpieler2;
    private javax.swing.JLabel jLabelAutoSpieler1;
    private javax.swing.JLabel jLabelAutoSpieler2;
    private javax.swing.JPanel jPanelFahrbahn1;
    private javax.swing.JPanel jPanelFahrbahn2;
    private javax.swing.JProgressBar jProgressBarSpeedSpieler2;
    private javax.swing.JTextField jTextFieldNextStepSpieler2;
    // End of variables declaration//GEN-END:variables
}
